# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bolsistas_praec', '0002_auto_20171103_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('siape', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
